name: disent
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - matplotlib=3.7
  - scipy=1.11
  - numpy=1.25
  - pytorch=2.0
  - ipympl=0.9
  - jupyterlab=4.2
  - ipywidgets=8.1
  - notebook=7.2
