name: disent
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.14
  - matplotlib=3.7.3
  - scipy=1.11.4
  - numpy=1.25.2
  - pytorch=2.0.0
  - ipympl=0.9.4
  - jupyterlab=4.2.1
  - ipywidgets=8.1.3
  - notebook=7.2.0
  - tqdm=4.66.4
